export const HALAL_CATEGORIES = [
  { id: "gaming", name: "Gaming", nameAr: "ألعاب", slug: "gaming", icon: "🎮" },
  {
    id: "education",
    name: "Education",
    nameAr: "تعليم",
    slug: "education",
    icon: "📚",
  },
  {
    id: "talk-shows",
    name: "Talk Shows",
    nameAr: "برامج حوارية",
    slug: "talk-shows",
    icon: "🎙️",
  },
  {
    id: "cooking",
    name: "Cooking",
    nameAr: "طبخ",
    slug: "cooking",
    icon: "🍳",
  },
  { id: "sports", name: "Sports", nameAr: "رياضة", slug: "sports", icon: "⚽" },
  {
    id: "technology",
    name: "Technology",
    nameAr: "تكنولوجيا",
    slug: "technology",
    icon: "💻",
  },
  {
    id: "art-design",
    name: "Art & Design",
    nameAr: "فن وتصميم",
    slug: "art-design",
    icon: "🎨",
  },
  {
    id: "fitness",
    name: "Fitness",
    nameAr: "لياقة بدنية",
    slug: "fitness",
    icon: "💪",
  },
  {
    id: "islamic",
    name: "Islamic Content",
    nameAr: "محتوى إسلامي",
    slug: "islamic",
    icon: "🕌",
  },
  { id: "travel", name: "Travel", nameAr: "سفر", slug: "travel", icon: "✈️" },
  {
    id: "science",
    name: "Science",
    nameAr: "علوم",
    slug: "science",
    icon: "🔬",
  },
  {
    id: "languages",
    name: "Languages",
    nameAr: "لغات",
    slug: "languages",
    icon: "🗣️",
  },
  {
    id: "crafts",
    name: "Crafts & DIY",
    nameAr: "حرف يدوية",
    slug: "crafts",
    icon: "🧶",
  },
  {
    id: "family",
    name: "Family & Kids",
    nameAr: "عائلة وأطفال",
    slug: "family",
    icon: "👨‍👩‍👧‍👦",
  },
  {
    id: "business",
    name: "Business",
    nameAr: "أعمال",
    slug: "business",
    icon: "💼",
  },
  {
    id: "just-chatting",
    name: "Just Chatting",
    nameAr: "دردشة",
    slug: "just-chatting",
    icon: "💬",
  },
] as const;

export type CategoryId = (typeof HALAL_CATEGORIES)[number]["id"];
