// Mock data for the Habibi Stream web app
// This simulates the API responses until the backend is built

export const MOCK_STREAMS = [
  {
    id: "stream-1",
    creatorId: "user-1",
    creatorName: "أحمد الغامدي",
    creatorAvatarUrl: "https://api.dicebear.com/9.x/adventurer/svg?seed=Ahmed",
    isCreatorVerified: true,
    title: "بث مباشر: فورتنايت مع المتابعين 🎮",
    categoryId: "gaming",
    categoryName: "ألعاب",
    thumbnailUrl: "https://picsum.photos/seed/stream1/640/360",
    status: "live" as const,
    viewerCount: 2847,
    startedAt: new Date(Date.now() - 3600000).toISOString(),
    tags: ["فورتنايت", "ألعاب", "بث_عائلي"],
  },
  {
    id: "stream-2",
    creatorId: "user-2",
    creatorName: "سارة المهندسة",
    creatorAvatarUrl: "https://api.dicebear.com/9.x/adventurer/svg?seed=Sara",
    isCreatorVerified: true,
    title: "تعلم البرمجة من الصفر — حلقة 12 💻",
    categoryId: "technology",
    categoryName: "تكنولوجيا",
    thumbnailUrl: "https://picsum.photos/seed/stream2/640/360",
    status: "live" as const,
    viewerCount: 1523,
    startedAt: new Date(Date.now() - 7200000).toISOString(),
    tags: ["برمجة", "تعليم", "تكنولوجيا"],
  },
  {
    id: "stream-3",
    creatorId: "user-3",
    creatorName: "محمد الطباخ",
    creatorAvatarUrl:
      "https://api.dicebear.com/9.x/adventurer/svg?seed=Mohammed",
    isCreatorVerified: false,
    title: "وصفة كبسة لحم على أصولها 🍖",
    categoryId: "cooking",
    categoryName: "طبخ",
    thumbnailUrl: "https://picsum.photos/seed/stream3/640/360",
    status: "live" as const,
    viewerCount: 892,
    startedAt: new Date(Date.now() - 1800000).toISOString(),
    tags: ["طبخ", "كبسة", "مطبخ_عربي"],
  },
  {
    id: "stream-4",
    creatorId: "user-4",
    creatorName: "نور العلم",
    creatorAvatarUrl: "https://api.dicebear.com/9.x/adventurer/svg?seed=Noor",
    isCreatorVerified: true,
    title: "مراجعة دروس الرياضيات — الصف الثالث ثانوي 📚",
    categoryId: "education",
    categoryName: "تعليم",
    thumbnailUrl: "https://picsum.photos/seed/stream4/640/360",
    status: "live" as const,
    viewerCount: 3201,
    startedAt: new Date(Date.now() - 5400000).toISOString(),
    tags: ["تعليم", "رياضيات", "ثانوي"],
  },
  {
    id: "stream-5",
    creatorId: "user-5",
    creatorName: "كابتن فهد",
    creatorAvatarUrl: "https://api.dicebear.com/9.x/adventurer/svg?seed=Fahd",
    isCreatorVerified: false,
    title: "تمارين منزلية للياقة البدنية 💪",
    categoryId: "fitness",
    categoryName: "لياقة بدنية",
    thumbnailUrl: "https://picsum.photos/seed/stream5/640/360",
    status: "live" as const,
    viewerCount: 678,
    startedAt: new Date(Date.now() - 2700000).toISOString(),
    tags: ["رياضة", "لياقة", "تمارين"],
  },
  {
    id: "stream-6",
    creatorId: "user-6",
    creatorName: "ياسمين الفنانة",
    creatorAvatarUrl:
      "https://api.dicebear.com/9.x/adventurer/svg?seed=Yasmine",
    isCreatorVerified: true,
    title: "رسم بورتريه مباشر — ارسل صورتك! 🎨",
    categoryId: "art-design",
    categoryName: "فن وتصميم",
    thumbnailUrl: "https://picsum.photos/seed/stream6/640/360",
    status: "live" as const,
    viewerCount: 1156,
    startedAt: new Date(Date.now() - 4500000).toISOString(),
    tags: ["فن", "رسم", "بورتريه"],
  },
  {
    id: "stream-7",
    creatorId: "user-7",
    creatorName: "شيخ عبدالله",
    creatorAvatarUrl:
      "https://api.dicebear.com/9.x/adventurer/svg?seed=Abdullah",
    isCreatorVerified: true,
    title: "تفسير سورة الكهف — الجزء الثاني 🕌",
    categoryId: "islamic",
    categoryName: "محتوى إسلامي",
    thumbnailUrl: "https://picsum.photos/seed/stream7/640/360",
    status: "live" as const,
    viewerCount: 5432,
    startedAt: new Date(Date.now() - 3000000).toISOString(),
    tags: ["إسلامي", "تفسير", "قرآن"],
  },
  {
    id: "stream-8",
    creatorId: "user-8",
    creatorName: "علي الرحال",
    creatorAvatarUrl: "https://api.dicebear.com/9.x/adventurer/svg?seed=Ali",
    isCreatorVerified: false,
    title: "جولة مباشرة في أسواق إسطنبول 🇹🇷",
    categoryId: "travel",
    categoryName: "سفر",
    thumbnailUrl: "https://picsum.photos/seed/stream8/640/360",
    status: "live" as const,
    viewerCount: 1890,
    startedAt: new Date(Date.now() - 6000000).toISOString(),
    tags: ["سفر", "تركيا", "إسطنبول"],
  },
  {
    id: "stream-9",
    creatorId: "user-9",
    creatorName: "جيمر خالد",
    creatorAvatarUrl: "https://api.dicebear.com/9.x/adventurer/svg?seed=Khaled",
    isCreatorVerified: false,
    title: "بطولة روكيت ليق مع الأصدقاء 🚗",
    categoryId: "gaming",
    categoryName: "ألعاب",
    thumbnailUrl: "https://picsum.photos/seed/stream9/640/360",
    status: "live" as const,
    viewerCount: 445,
    startedAt: new Date(Date.now() - 900000).toISOString(),
    tags: ["ألعاب", "روكيت_ليق"],
  },
  {
    id: "stream-10",
    creatorId: "user-10",
    creatorName: "أم سلمى",
    creatorAvatarUrl:
      "https://api.dicebear.com/9.x/adventurer/svg?seed=UmSalma",
    isCreatorVerified: false,
    title: "حرف يدوية جميلة للأطفال — كروشيه 🧶",
    categoryId: "crafts",
    categoryName: "حرف يدوية",
    thumbnailUrl: "https://picsum.photos/seed/stream10/640/360",
    status: "live" as const,
    viewerCount: 334,
    startedAt: new Date(Date.now() - 4200000).toISOString(),
    tags: ["حرف_يدوية", "كروشيه", "أطفال"],
  },
  {
    id: "stream-11",
    creatorId: "user-11",
    creatorName: "دكتور وليد",
    creatorAvatarUrl: "https://api.dicebear.com/9.x/adventurer/svg?seed=Walid",
    isCreatorVerified: true,
    title: "دردشة مفتوحة — اسأل أي سؤال! 💬",
    categoryId: "just-chatting",
    categoryName: "دردشة",
    thumbnailUrl: "https://picsum.photos/seed/stream11/640/360",
    status: "live" as const,
    viewerCount: 2100,
    startedAt: new Date(Date.now() - 1200000).toISOString(),
    tags: ["دردشة", "سؤال_وجواب"],
  },
  {
    id: "stream-12",
    creatorId: "user-12",
    creatorName: "ريان البزنس",
    creatorAvatarUrl: "https://api.dicebear.com/9.x/adventurer/svg?seed=Rayan",
    isCreatorVerified: true,
    title: "كيف تبدأ مشروعك الخاص في 2025 💼",
    categoryId: "business",
    categoryName: "أعمال",
    thumbnailUrl: "https://picsum.photos/seed/stream12/640/360",
    status: "live" as const,
    viewerCount: 1780,
    startedAt: new Date(Date.now() - 3300000).toISOString(),
    tags: ["أعمال", "ريادة", "مشاريع"],
  },
];

export const MOCK_CHAT_MESSAGES = [
  {
    id: "msg-1",
    streamId: "stream-1",
    userId: "user-20",
    displayName: "عمر",
    avatarUrl: "https://api.dicebear.com/9.x/adventurer/svg?seed=Omar",
    content: "ماشاء الله عليك! 🔥",
    type: "text" as const,
    isSubscriber: true,
    isCreator: false,
    isModerator: false,
    timestamp: new Date(Date.now() - 30000).toISOString(),
  },
  {
    id: "msg-2",
    streamId: "stream-1",
    userId: "user-21",
    displayName: "فاطمة",
    avatarUrl: "https://api.dicebear.com/9.x/adventurer/svg?seed=Fatima",
    content: "أهلاً بالجميع ❤️",
    type: "text" as const,
    isSubscriber: false,
    isCreator: false,
    isModerator: false,
    timestamp: new Date(Date.now() - 25000).toISOString(),
  },
  {
    id: "msg-3",
    streamId: "stream-1",
    userId: "user-22",
    displayName: "خالد",
    avatarUrl: "https://api.dicebear.com/9.x/adventurer/svg?seed=KhaledChat",
    content: "يا سلام على اللعب!",
    type: "text" as const,
    isSubscriber: true,
    isCreator: false,
    isModerator: true,
    timestamp: new Date(Date.now() - 20000).toISOString(),
  },
  {
    id: "msg-4",
    streamId: "stream-1",
    userId: "user-23",
    displayName: "مريم",
    avatarUrl: "https://api.dicebear.com/9.x/adventurer/svg?seed=Mariam",
    content: "أول مرة أشاهدك — محتوى رائع 👏",
    type: "text" as const,
    isSubscriber: false,
    isCreator: false,
    isModerator: false,
    timestamp: new Date(Date.now() - 15000).toISOString(),
  },
  {
    id: "msg-5",
    streamId: "stream-1",
    userId: "user-24",
    displayName: "يوسف",
    avatarUrl: "https://api.dicebear.com/9.x/adventurer/svg?seed=Youssef",
    content: "من السعودية نحبك ❤️🇸🇦",
    type: "text" as const,
    isSubscriber: false,
    isCreator: false,
    isModerator: false,
    timestamp: new Date(Date.now() - 10000).toISOString(),
  },
  {
    id: "msg-6",
    streamId: "stream-1",
    userId: "user-1",
    displayName: "أحمد الغامدي",
    avatarUrl: "https://api.dicebear.com/9.x/adventurer/svg?seed=Ahmed",
    content: "أهلاً فيكم جميعاً! شكراً على الدعم 💜",
    type: "text" as const,
    isSubscriber: false,
    isCreator: true,
    isModerator: false,
    timestamp: new Date(Date.now() - 5000).toISOString(),
  },
  {
    id: "msg-7",
    streamId: "stream-1",
    userId: "user-25",
    displayName: "هناء",
    avatarUrl: "https://api.dicebear.com/9.x/adventurer/svg?seed=Hanaa",
    content: "🔥🔥🔥",
    type: "text" as const,
    isSubscriber: true,
    isCreator: false,
    isModerator: false,
    timestamp: new Date(Date.now() - 3000).toISOString(),
  },
];

export const MOCK_CURRENT_USER = {
  id: "current-user",
  email: "viewer@habibi.stream",
  displayName: "مشاهد حبيبي",
  avatarUrl: "https://api.dicebear.com/9.x/adventurer/svg?seed=Viewer",
  bio: "محب للمحتوى العربي الهادف",
  followerCount: 12,
  followingCount: 45,
  isLive: false,
  isVerified: false,
  isCreator: false,
  walletBalance: 1250,
  createdAt: "2025-01-01T00:00:00Z",
  updatedAt: "2025-02-25T00:00:00Z",
};
